### ISSUE TITLE
How to use the sensor replay on the emulator?

### ISSUE THREAD

**Issue by MMeram** [nkh-lab/car-api-hello-world#1]
Hi,

I wonder how you simulated speed and gear change on the emulator. I did a quick search but did not find any useful info.

I'd appreciate if you can give some hints on that.

Thank you 
Besr regards

**Comment by nkh-lab** [comment]
For changing speed and gear go to emulator 'Extended Controls' by pressing three dots (...) and change values on 'Car data' tab in the corresponding fields.

**Comment by nkh-lab** [comment]
Not an issue, closed.
