### ISSUE TITLE
build fails with "MainActivity.java:59: Error: Overriding method should call super.onRequestPermissionsResult [MissingSuperCall]"

### ISSUE THREAD

**Issue by rmie** [nkh-lab/car-api-hello-world#3]
I'm trying to build this as I want to get a glimpse on what my new car is exposing via CarPropertyManager.
Please let me know it this app could work at all for this purpose.

Additionally, I'm an Android noob, not having done any Android development at all before. I forked your repo and added a build action.

[Building fails](https://github.com/rmie/car-api-hello-world/actions/runs/5676989471/job/15384571911) with
```
app/src/main/java/com/example/carapihelloworld/MainActivity.java:59: Error: Overriding method should call super.onRequestPermissionsResult [MissingSuperCall]
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "MissingSuperCall":
   Some methods, such as View#onDetachedFromWindow, require that you also call
   the super implementation as part of your method.
```

I tried to fix it with a [commit](https://github.com/nkh-lab/car-api-hello-world/commit/997ce5450bc8122959c8d41e6c3c9ea5ed5040d7) like:
```
      public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
+         super.onRequestPermissionsResult(requestCode, permissions, grantResults);
          if (requestCode == REQUEST_CODE_ASK_PERMISSIONS) {
              //all permissions have been granted
```

but then that app crashes when I try to run it on my phone connected to the car.

**Comment by nkh-lab** [comment]
This project is not for generic Android like on your phone, but for Android Automotive (generic Android + CAR API and other automotive extensions) which is used by automakers in their IVI systems.

**Comment by rmie** [comment]
@nkh-lab ok, understood, thanks for clarification

**Comment by nkh-lab** [comment]
Closed. Wrong usage.
